name: Docker CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - fuentes/**
  pull_request:
    branches: [ main ]
    paths:
      - fuentes/**

jobs:
  build:
    name: build and push Docker image
    runs-on: ubuntu-latest
    steps: 
      # 1 
      - uses: actions/checkout@v4
      # 2  
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DH_USER_FIN }}
          password: ${{ secrets.DH_TOKEN_FIN }}
      # 3   
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true 
          tags: ${{ secrets.DH_USER_FIN }}/galeria:latest

  # cÃ³digo aÃ±adido
  aws:
    name: Deploy image to aws
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # 1
    - name: copy docker compose via ssh key  
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_IP_FIN }}
        username: ${{ secrets.AC2_USER_FIN }}
        port: 22 # ${{ secrets.PORT }}
        key: ${{ secrets.EC2_KEY_FIN }}
        source: "docker-compose.yml"
        target: /ubuntu/admin
    # 2
    - name: script deploy docker services 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AC2_IP_FIN }}
        username: ${{ secrets.EC2_USER_FIN }}
        key: ${{ secrets.EC2_KEY_FIN }}
        port: 22  # ${{ secrets.PORT }}
        script: |
            sleep 60
            docker compose down --rmi all
            docker compose up -d
